### ISSUE TITLE
Doesn't  handle special chars in productnames etc

### ISSUE THREAD

**Issue by syntaxerror** [DIBS-Payment-Services/Opencart#5]
Tested the DX version for OC2 and noticed it doesn't handle special chars in product names, and probably in other fields - the HMAC calculation will fail.

T.ex isn't this product name accepted: Apple Cinema 20" Display
- because of the double quote.

Old bug in a new module. ;)

**Comment by maxwhite** [comment]
Thank you, now it is fixed
